-- SÓCRATES DS V1.7 — Meta-Professor Engine
-- Generic longitudinal teaching orchestration. Machine Learning is the first complete track.
-- Reuses existing concepts, mastery, attempts, reviews and misconceptions instead of creating a parallel learning model.

create table if not exists public.sds_learning_tracks (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  domain text not null,
  description text not null,
  objective text not null,
  version text not null default '1.0.0',
  status text not null default 'active'
    check (status in ('draft','active','archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sds_track_concepts (
  track_id uuid not null references public.sds_learning_tracks(id) on delete cascade,
  concept_id uuid not null references public.sds_concepts(id) on delete cascade,
  sequence integer not null check (sequence > 0),
  phase text not null,
  role text not null default 'core'
    check (role in ('core','stretch','capstone')),
  required boolean not null default true,
  target_stage public.sds_learning_stage not null default 'applied',
  min_evidence integer not null default 1 check (min_evidence >= 0),
  preferred_course_id uuid references public.sds_courses(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  primary key (track_id, concept_id),
  unique (track_id, sequence)
);

create table if not exists public.sds_professor_states (
  user_id uuid not null references auth.users(id) on delete cascade,
  track_id uuid not null references public.sds_learning_tracks(id) on delete cascade,
  current_concept_id uuid references public.sds_concepts(id) on delete set null,
  status text not null default 'active'
    check (status in ('active','paused','completed')),
  assistance_ceiling smallint not null default 3 check (assistance_ceiling between 0 and 5),
  missions_completed integer not null default 0 check (missions_completed >= 0),
  autonomous_attempts integer not null default 0 check (autonomous_attempts >= 0),
  hints_used integer not null default 0 check (hints_used >= 0),
  solutions_revealed integer not null default 0 check (solutions_revealed >= 0),
  last_mission_at timestamptz,
  last_evidence_at timestamptz,
  policy jsonb not null default jsonb_build_object(
    'help_ladder', jsonb_build_array(
      'cold_attempt',
      'socratic_question',
      'conceptual_hint',
      'structure_or_pseudocode',
      'partial_solution',
      'reference_solution'
    ),
    'solution_requires_attempt', true,
    'mastery_requires_evidence', true
  ),
  updated_at timestamptz not null default now(),
  primary key (user_id, track_id)
);

create table if not exists public.sds_professor_missions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  track_id uuid not null references public.sds_learning_tracks(id) on delete cascade,
  concept_id uuid not null references public.sds_concepts(id) on delete cascade,
  course_id uuid references public.sds_courses(id) on delete set null,
  question_id uuid references public.sds_question_bank(id) on delete set null,
  mission_type text not null
    check (mission_type in ('diagnostic','practice','debug','transfer','retention','oral_defense')),
  objective text not null,
  reason text not null,
  target_dimension text not null
    check (target_dimension in ('conceptual','mathematical','coding','transfer','retention')),
  difficulty smallint not null default 2 check (difficulty between 1 and 5),
  assistance_ceiling smallint not null default 2 check (assistance_ceiling between 0 and 5),
  expected_evidence jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued','in_progress','completed','abandoned')),
  started_at timestamptz,
  completed_at timestamptz,
  outcome jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (completed_at is null or started_at is null or completed_at >= started_at)
);

create table if not exists public.sds_professor_assistance_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mission_id uuid not null references public.sds_professor_missions(id) on delete cascade,
  level smallint not null check (level between 0 and 5),
  event_type text not null
    check (event_type in (
      'cold_attempt',
      'hint_requested',
      'hint_shown',
      'structure_requested',
      'structure_shown',
      'partial_solution',
      'reference_solution',
      'reflection'
    )),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists sds_idx_track_concepts_sequence
  on public.sds_track_concepts(track_id, sequence);
create index if not exists sds_idx_professor_missions_user_recent
  on public.sds_professor_missions(user_id, created_at desc);
create index if not exists sds_idx_professor_missions_track_status
  on public.sds_professor_missions(user_id, track_id, status);
create index if not exists sds_idx_professor_assistance_mission
  on public.sds_professor_assistance_events(mission_id, occurred_at);
create index if not exists sds_idx_professor_states_user
  on public.sds_professor_states(user_id, updated_at desc);

drop trigger if exists sds_learning_tracks_updated_at on public.sds_learning_tracks;
create trigger sds_learning_tracks_updated_at
before update on public.sds_learning_tracks
for each row execute function public.sds_set_updated_at();

drop trigger if exists sds_professor_states_updated_at on public.sds_professor_states;
create trigger sds_professor_states_updated_at
before update on public.sds_professor_states
for each row execute function public.sds_set_updated_at();

alter table public.sds_learning_tracks enable row level security;
alter table public.sds_track_concepts enable row level security;
alter table public.sds_professor_states enable row level security;
alter table public.sds_professor_missions enable row level security;
alter table public.sds_professor_assistance_events enable row level security;

revoke all on table public.sds_learning_tracks from anon, authenticated;
revoke all on table public.sds_track_concepts from anon, authenticated;
revoke all on table public.sds_professor_states from anon, authenticated;
revoke all on table public.sds_professor_missions from anon, authenticated;
revoke all on table public.sds_professor_assistance_events from anon, authenticated;

grant select on table public.sds_learning_tracks to authenticated;
grant select on table public.sds_track_concepts to authenticated;
grant select, insert, update, delete on table public.sds_professor_states to authenticated;
grant select, insert, update, delete on table public.sds_professor_missions to authenticated;
grant select, insert on table public.sds_professor_assistance_events to authenticated;
grant usage, select on sequence public.sds_professor_assistance_events_id_seq to authenticated;

drop policy if exists "sds learning tracks read" on public.sds_learning_tracks;
create policy "sds learning tracks read"
on public.sds_learning_tracks for select to authenticated using (status = 'active');

drop policy if exists "sds track concepts read" on public.sds_track_concepts;
create policy "sds track concepts read"
on public.sds_track_concepts for select to authenticated using (true);

drop policy if exists "sds professor state select own" on public.sds_professor_states;
create policy "sds professor state select own"
on public.sds_professor_states for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "sds professor state insert own" on public.sds_professor_states;
create policy "sds professor state insert own"
on public.sds_professor_states for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "sds professor state update own" on public.sds_professor_states;
create policy "sds professor state update own"
on public.sds_professor_states for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
drop policy if exists "sds professor state delete own" on public.sds_professor_states;
create policy "sds professor state delete own"
on public.sds_professor_states for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "sds professor missions select own" on public.sds_professor_missions;
create policy "sds professor missions select own"
on public.sds_professor_missions for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "sds professor missions insert own" on public.sds_professor_missions;
create policy "sds professor missions insert own"
on public.sds_professor_missions for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "sds professor missions update own" on public.sds_professor_missions;
create policy "sds professor missions update own"
on public.sds_professor_missions for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
drop policy if exists "sds professor missions delete own" on public.sds_professor_missions;
create policy "sds professor missions delete own"
on public.sds_professor_missions for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "sds professor assistance select own" on public.sds_professor_assistance_events;
create policy "sds professor assistance select own"
on public.sds_professor_assistance_events for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "sds professor assistance insert own" on public.sds_professor_assistance_events;
create policy "sds professor assistance insert own"
on public.sds_professor_assistance_events for insert to authenticated
with check ((select auth.uid()) = user_id);

-- First complete vertical: Applied ML → Decision Intelligence.
insert into public.sds_learning_tracks (
  slug, name, domain, description, objective, version, status, metadata
)
values (
  'applied-ml-decision-intelligence',
  'Applied ML — Decision Intelligence',
  'Machine Learning',
  'A longitudinal track from baselines and validation to causal ML, monitoring and decision systems.',
  'Move from using models to being able to specify, implement, diagnose, defend and operationalize them with evidence.',
  '1.0.0',
  'active',
  jsonb_build_object(
    'first_complete_vertical', true,
    'teaching_style', 'socratic_adaptive',
    'evidence_policy', 'mastery_requires_attempts_transfer_and_retention'
  )
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  objective = excluded.objective,
  version = excluded.version,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.sds_concepts (canonical_key, title, description, difficulty, tags)
values
  ('baseline-models', 'Baselines y criterio de mejora', 'Construir una referencia simple antes de añadir complejidad y definir qué significa mejorar.', 2, array['supervised','baseline','evaluation']),
  ('linear-regression', 'Regresión lineal aplicada', 'Especificación, supuestos, interpretación, diagnóstico y uso como baseline continuo.', 2, array['supervised','regression']),
  ('logistic-regression', 'Regresión logística aplicada', 'Probabilidades, log-odds, clasificación, calibración y baseline interpretable.', 3, array['supervised','classification']),
  ('decision-trees', 'Árboles de decisión', 'Particiones, impureza, profundidad, regularización y sobreajuste.', 3, array['supervised','trees']),
  ('decision-thresholds', 'Thresholding y costos de decisión', 'Convertir probabilidades en acciones usando costos, capacidad y utilidad esperada.', 4, array['decision-intelligence','classification','thresholds']),
  ('error-analysis', 'Error analysis por slices', 'Examinar falsos positivos, falsos negativos y degradación por segmentos antes de cambiar de algoritmo.', 4, array['evaluation','diagnostics','decision-intelligence']),
  ('survival-analysis', 'Survival analysis', 'Tiempo hasta evento, censura, hazard y predicción temporal de eventos.', 4, array['survival','time-to-event']),
  ('causal-inference', 'Causal inference para decisiones', 'Separar asociación, predicción y efecto causal para decisiones contrafactuales.', 5, array['causal','econometrics','decision-intelligence']),
  ('uplift-modeling', 'Uplift y heterogeneous treatment effects', 'Priorizar intervenciones por efecto incremental esperado y no solo por propensión.', 5, array['causal','uplift','decision-intelligence']),
  ('model-drift', 'Model drift y monitoreo', 'Distinguir drift de covariables, predicciones, conceptos y performance en producción.', 4, array['mlops','monitoring']),
  ('champion-challenger', 'Champion / Challenger', 'Comparar modelos y políticas con gates, holdouts y criterios explícitos de promoción.', 4, array['experimentation','mlops','decision-intelligence']),
  ('decision-systems', 'Predicción → decisión → acción → outcome', 'Cerrar el loop entre score, policy, intervención, resultado observado y aprendizaje.', 5, array['decision-intelligence','experimentation','systems'])
on conflict (canonical_key) do nothing;

with track as (
  select id from public.sds_learning_tracks where slug = 'applied-ml-decision-intelligence'
),
mapped(concept_key, sequence, phase, role, target_stage, min_evidence, course_slug) as (
  values
    ('baseline-models', 1, 'foundations', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('linear-regression', 2, 'foundations', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('logistic-regression', 3, 'foundations', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('train-validation-test', 4, 'validation', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('data-leakage', 5, 'validation', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('classification-metrics', 6, 'evaluation', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('bias-variance', 7, 'evaluation', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('regularization', 8, 'modeling', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('decision-trees', 9, 'modeling', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-fundamentals'),
    ('ensembles-boosting', 10, 'modeling', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('calibration', 11, 'evaluation', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('decision-thresholds', 12, 'decision', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('model-interpretability', 13, 'evaluation', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('error-analysis', 14, 'evaluation', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('time-series-validation', 15, 'validation', 'core', 'transferred'::public.sds_learning_stage, 1, 'forecasting-for-data-science'),
    ('survival-analysis', 16, 'advanced', 'stretch', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('causal-inference', 17, 'causal', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('uplift-modeling', 18, 'causal', 'stretch', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('model-drift', 19, 'operations', 'core', 'applied'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('champion-challenger', 20, 'operations', 'core', 'transferred'::public.sds_learning_stage, 1, 'ml-supervisado-advanced'),
    ('decision-systems', 21, 'capstone', 'capstone', 'transferred'::public.sds_learning_stage, 2, 'proyecto-integrador-tesis')
)
insert into public.sds_track_concepts (
  track_id, concept_id, sequence, phase, role, required, target_stage, min_evidence, preferred_course_id, metadata
)
select
  track.id,
  c.id,
  mapped.sequence,
  mapped.phase,
  mapped.role,
  true,
  mapped.target_stage,
  mapped.min_evidence,
  crs.id,
  jsonb_build_object('course_slug', mapped.course_slug)
from track
join mapped on true
join public.sds_concepts c on c.canonical_key = mapped.concept_key
left join public.sds_courses crs on crs.slug = mapped.course_slug
on conflict (track_id, concept_id) do update set
  sequence = excluded.sequence,
  phase = excluded.phase,
  role = excluded.role,
  required = excluded.required,
  target_stage = excluded.target_stage,
  min_evidence = excluded.min_evidence,
  preferred_course_id = excluded.preferred_course_id,
  metadata = excluded.metadata;

-- Make every track concept discoverable from its preferred course.
insert into public.sds_course_concepts (course_id, concept_id, module, role)
select
  tc.preferred_course_id,
  tc.concept_id,
  tc.phase,
  case when tc.role = 'stretch' then 'supporting' else 'core' end
from public.sds_track_concepts tc
join public.sds_learning_tracks t on t.id = tc.track_id
where t.slug = 'applied-ml-decision-intelligence'
  and tc.preferred_course_id is not null
on conflict (course_id, concept_id) do nothing;

with seed(concept_key, course_slug, mode, dimension, difficulty, prompt, answer_guide) as (
  values
    ('baseline-models','ml-supervisado-fundamentals','socratic'::public.sds_session_mode,'conceptual',2,
      'Antes de entrenar un modelo complejo para predecir conversión, ¿qué baseline construirías y qué tendría que superar el modelo?',
      'Debe proponer una referencia simple y reproducible —por ejemplo prevalencia, regla heurística o modelo lineal/logístico simple— y una métrica ligada a la decisión. La mejora debe compararse fuera de muestra, no solo en train.'),
    ('linear-regression','ml-supervisado-fundamentals','feynman'::public.sds_session_mode,'mathematical',2,
      'Explica qué estima OLS y qué información de los residuos revisarías antes de confiar en una regresión lineal.',
      'OLS minimiza la suma de residuos cuadrados. Debe distinguir ajuste de supuestos/diagnóstico y mencionar patrones de residuos, heterocedasticidad, outliers o mala especificación según el objetivo.'),
    ('logistic-regression','ml-supervisado-fundamentals','feynman'::public.sds_session_mode,'conceptual',3,
      '¿Qué significa un coeficiente positivo en regresión logística y por qué no equivale directamente a un aumento constante en probabilidad?',
      'El coeficiente actúa sobre log-odds. El efecto en probabilidad depende del punto de partida y demás covariables; la relación no es lineal en la escala de probabilidad.'),
    ('train-validation-test','ml-supervisado-fundamentals','examiner'::public.sds_session_mode,'transfer',3,
      'Tienes leads de enero de 2024 a agosto de 2026 y el modelo operará en septiembre de 2026. Diseña un split que imite producción.',
      'Debe preservar el orden temporal, usar pasado para entrenar, un periodo posterior para selección/tuning y el tramo más reciente como test final. No debe mezclar observaciones futuras en entrenamiento.'),
    ('data-leakage','ml-supervisado-fundamentals','examiner'::public.sds_session_mode,'transfer',3,
      'Quieres predecir una separación en el momento t0 de creación del lead. ¿Cómo auditarías si una variable produce leakage?',
      'Debe preguntar si la variable o su transformación existirían exactamente en t0, revisar timestamps y linaje, y excluir información posterior al outcome o construida con ventanas que miran al futuro.'),
    ('classification-metrics','ml-supervisado-fundamentals','socratic'::public.sds_session_mode,'transfer',3,
      'En un problema con 5% de conversión, ¿por qué accuracy puede ser engañosa y qué métricas mirarías según el costo comercial?',
      'Debe reconocer desbalance; precision y recall responden a costos distintos, PR-AUC puede ser más informativa, y la métrica final debe conectarse con capacidad y costos de falsos positivos/negativos.'),
    ('bias-variance','ml-supervisado-fundamentals','socratic'::public.sds_session_mode,'transfer',3,
      'Tu modelo logra 99% en train y 71% en validación. ¿Qué investigarías antes de cambiar de algoritmo?',
      'Debe sospechar alta varianza/overfitting, revisar leakage, split, complejidad, regularización, tamaño de muestra y estabilidad por segmentos antes de saltar de modelo.'),
    ('regularization','ml-supervisado-fundamentals','feynman'::public.sds_session_mode,'mathematical',3,
      'Compara L1 y L2: ¿qué penalizan y qué comportamiento inducen sobre los coeficientes?',
      'Ambas penalizan complejidad. L1 usa magnitudes absolutas y puede llevar coeficientes exactamente a cero; L2 usa cuadrados y contrae coeficientes de forma suave.'),
    ('decision-trees','ml-supervisado-fundamentals','socratic'::public.sds_session_mode,'coding',3,
      'Un árbol memoriza casi perfectamente el train. ¿Qué hiperparámetros y señales revisarías para reducir sobreajuste?',
      'Debe mencionar profundidad, tamaño mínimo de hoja/split, poda o complejidad y comparar curvas train/validation con validación apropiada.'),
    ('ensembles-boosting','ml-supervisado-advanced','feynman'::public.sds_session_mode,'conceptual',4,
      'Explica la diferencia esencial entre bagging y boosting y qué tipo de error intenta reducir cada enfoque.',
      'Bagging entrena modelos en paralelo sobre variaciones de datos y reduce varianza; boosting construye secuencialmente corrigiendo errores/residuos y puede reducir sesgo, con riesgo de sobreajuste si se fuerza demasiado.'),
    ('calibration','ml-supervisado-advanced','examiner'::public.sds_session_mode,'transfer',4,
      'Un modelo tiene AUC 0.87. Para leads con score 0.8–0.9 la conversión real es 51%. ¿Qué conclusión puedes y no puedes sacar?',
      'Puede tener buena discriminación pero mala calibración. No debe interpretar 0.8 como 80% real sin verificar reliability/calibration. AUC no garantiza probabilidades calibradas.'),
    ('decision-thresholds','ml-supervisado-advanced','socratic'::public.sds_session_mode,'transfer',4,
      'Tienes capacidad para llamar solo al 10% de leads. ¿Cómo convertirías probabilidades en una policy de contacto?',
      'Debe separar modelo de policy, considerar ranking, costos/beneficios, capacidad, lift/top-decile, threshold o cuota y validar la decisión con outcomes, idealmente experimento.'),
    ('model-interpretability','ml-supervisado-advanced','examiner'::public.sds_session_mode,'conceptual',4,
      'SHAP indica que una variable elevó el score de un lead. ¿Por qué eso no demuestra que intervenir sobre esa variable causará una conversión?',
      'SHAP explica la predicción del modelo bajo sus supuestos de atribución; no identifica efectos causales ni garantiza que cambiar una feature cambie el outcome.'),
    ('error-analysis','ml-supervisado-advanced','examiner'::public.sds_session_mode,'transfer',4,
      'Tu AUC global es buena, pero el negocio dice que el modelo falla. Diseña un error analysis antes de reentrenar.',
      'Debe inspeccionar FP/FN y calibración, segmentar por canal/proyecto/tiempo/u otros slices relevantes, revisar ejemplos individuales y buscar patrones operativos o drift antes de cambiar el algoritmo.'),
    ('time-series-validation','forecasting-for-data-science','examiner'::public.sds_session_mode,'transfer',4,
      '¿Por qué un random split puede invalidar una evaluación temporal y qué alternativa usarías?',
      'El random split puede filtrar información futura y romper dependencia temporal. Debe usar holdout cronológico, rolling/expanding windows o backtesting que imite el momento real de predicción.'),
    ('survival-analysis','ml-supervisado-advanced','feynman'::public.sds_session_mode,'conceptual',4,
      '¿Qué aporta survival analysis frente a una clasificación vender/no vender cuando muchas unidades aún no se han vendido?',
      'Modela tiempo hasta evento y maneja censura. Permite estimar survival/hazard o probabilidad de evento antes de un horizonte sin tratar casos aún abiertos como negativos definitivos.'),
    ('causal-inference','ml-supervisado-advanced','examiner'::public.sds_session_mode,'transfer',5,
      'El precio subió 5% y luego la absorción bajó 8%. ¿Por qué eso no identifica por sí solo una elasticidad causal?',
      'Puede haber confusión, selección, tendencias, shocks simultáneos, endogeneidad o cambios de mix. Se necesita una estrategia de identificación/contrafactual, no solo correlación antes-después.'),
    ('uplift-modeling','ml-supervisado-advanced','feynman'::public.sds_session_mode,'conceptual',5,
      'Distingue un lead con alta propensión de conversión de un lead con alto uplift esperado por una llamada.',
      'Propensión estima probabilidad de outcome dado X; uplift/CATE estima diferencia potencial entre tratamiento y control. Un lead de alta propensión puede convertir igual sin intervención.'),
    ('model-drift','ml-supervisado-advanced','examiner'::public.sds_session_mode,'transfer',4,
      'El score promedio cambió en producción. ¿Qué tipos de drift separarías antes de concluir que el modelo está roto?',
      'Debe separar cambios de covariables, distribución de scores, relación X→Y/concept drift y performance observada. Un cambio de inputs no implica automáticamente degradación de performance.'),
    ('champion-challenger','ml-supervisado-advanced','examiner'::public.sds_session_mode,'transfer',4,
      'Diseña un criterio de promoción para que un challenger reemplace al champion sin usar solo una métrica offline.',
      'Debe definir métricas offline y operativas, periodo/holdout o experimento, estabilidad y guardrails, criterios previos de promoción/rollback y evitar promover por una mejora accidental.'),
    ('decision-systems','proyecto-integrador-tesis','examiner'::public.sds_session_mode,'transfer',5,
      'Diseña el loop completo desde una predicción hasta aprendizaje operativo. ¿Qué registrarías para poder saber si el sistema creó valor?',
      'Debe conectar dato→predicción→policy/decisión→acción→outcome→feedback, registrar quién/qué/ cuándo, exposición o tratamiento, resultado, versión del modelo/policy y evidencia para comparar contra un contrafactual o baseline.')
)
insert into public.sds_question_bank (
  course_id, concept_id, mode, dimension, prompt, answer_guide, difficulty, active
)
select
  crs.id,
  c.id,
  seed.mode,
  seed.dimension,
  seed.prompt,
  seed.answer_guide,
  seed.difficulty,
  true
from seed
join public.sds_courses crs on crs.slug = seed.course_slug
join public.sds_concepts c on c.canonical_key = seed.concept_key
where not exists (
  select 1
  from public.sds_question_bank q
  where q.course_id = crs.id
    and q.concept_id = c.id
    and q.prompt = seed.prompt
);

create or replace function public.sds_meta_professor_track_summary(
  p_track_slug text default 'applied-ml-decision-intelligence'
)
returns table (
  track_id uuid,
  track_slug text,
  track_name text,
  total_concepts integer,
  concepts_with_evidence integer,
  proficient_concepts integer,
  completed_missions integer,
  assisted_missions integer,
  autonomy_ratio numeric
)
language sql
security invoker
set search_path = public
as $$
with chosen as (
  select t.id, t.slug, t.name
  from public.sds_learning_tracks t
  where t.slug = p_track_slug and t.status = 'active'
),
concept_stats as (
  select
    count(*)::integer as total_concepts,
    count(*) filter (where coalesce(ms.evidence_count, 0) > 0)::integer as concepts_with_evidence,
    count(*) filter (
      where (
        coalesce(ms.conceptual, 0) +
        coalesce(ms.mathematical, 0) +
        coalesce(ms.coding, 0) +
        coalesce(ms.transfer, 0) +
        coalesce(ms.retention, 0)
      ) / greatest(
        (ms.conceptual is not null)::int +
        (ms.mathematical is not null)::int +
        (ms.coding is not null)::int +
        (ms.transfer is not null)::int +
        (ms.retention is not null)::int,
        1
      ) >= 0.75
      and coalesce(ms.evidence_count, 0) >= tc.min_evidence
    )::integer as proficient_concepts
  from chosen
  join public.sds_track_concepts tc on tc.track_id = chosen.id
  left join public.sds_mastery_states ms
    on ms.user_id = (select auth.uid()) and ms.concept_id = tc.concept_id
),
mission_stats as (
  select
    count(*) filter (where m.status = 'completed')::integer as completed_missions,
    count(distinct m.id) filter (
      where m.status = 'completed'
        and exists (
          select 1
          from public.sds_professor_assistance_events ae
          where ae.mission_id = m.id
            and ae.user_id = (select auth.uid())
            and ae.level > 0
        )
    )::integer as assisted_missions
  from chosen
  left join public.sds_professor_missions m
    on m.track_id = chosen.id and m.user_id = (select auth.uid())
)
select
  chosen.id,
  chosen.slug,
  chosen.name,
  concept_stats.total_concepts,
  concept_stats.concepts_with_evidence,
  concept_stats.proficient_concepts,
  mission_stats.completed_missions,
  mission_stats.assisted_missions,
  case
    when mission_stats.completed_missions = 0 then null
    else round(
      1 - mission_stats.assisted_missions::numeric / mission_stats.completed_missions::numeric,
      4
    )
  end as autonomy_ratio
from chosen
cross join concept_stats
cross join mission_stats;
$$;

revoke execute on function public.sds_meta_professor_track_summary(text) from public, anon;
grant execute on function public.sds_meta_professor_track_summary(text) to authenticated;

create or replace function public.sds_meta_professor_next_mission(
  p_track_slug text default 'applied-ml-decision-intelligence'
)
returns table (
  track_id uuid,
  track_slug text,
  track_name text,
  concept_id uuid,
  concept_title text,
  course_id uuid,
  course_name text,
  question_id uuid,
  sequence integer,
  phase text,
  mission_type text,
  objective text,
  reason text,
  target_dimension text,
  difficulty smallint,
  assistance_ceiling smallint,
  mastery_average numeric,
  evidence_count integer,
  due_review boolean,
  open_misconception boolean
)
language sql
security invoker
set search_path = public
as $$
with chosen as (
  select t.id, t.slug, t.name
  from public.sds_learning_tracks t
  where t.slug = p_track_slug and t.status = 'active'
),
states as (
  select
    tc.*,
    c.title as concept_title,
    c.difficulty as concept_difficulty,
    ms.evidence_count,
    ms.conceptual,
    ms.mathematical,
    ms.coding,
    ms.transfer,
    ms.retention,
    (
      coalesce(ms.conceptual, 0) +
      coalesce(ms.mathematical, 0) +
      coalesce(ms.coding, 0) +
      coalesce(ms.transfer, 0) +
      coalesce(ms.retention, 0)
    )::numeric / greatest(
      (ms.conceptual is not null)::int +
      (ms.mathematical is not null)::int +
      (ms.coding is not null)::int +
      (ms.transfer is not null)::int +
      (ms.retention is not null)::int,
      1
    )::numeric as mastery_average,
    coalesce((
      select max(m.severity)
      from public.sds_misconceptions m
      where m.user_id = (select auth.uid())
        and m.concept_id = tc.concept_id
        and m.status in ('open','improving','reopened')
    ), 0) as misconception_severity,
    exists (
      select 1
      from public.sds_review_items r
      where r.user_id = (select auth.uid())
        and r.concept_id = tc.concept_id
        and r.status in ('scheduled','due')
        and r.due_at <= now()
    ) as due_review
  from chosen
  join public.sds_track_concepts tc on tc.track_id = chosen.id
  join public.sds_concepts c on c.id = tc.concept_id
  left join public.sds_mastery_states ms
    on ms.user_id = (select auth.uid()) and ms.concept_id = tc.concept_id
),
eligible as (
  select s.*
  from states s
  where not exists (
    select 1
    from states prev
    where prev.sequence < s.sequence
      and prev.required
      and (
        coalesce(prev.evidence_count, 0) < prev.min_evidence
        or prev.mastery_average < 0.55
      )
  )
),
ranked as (
  select
    e.*,
    case
      when e.misconception_severity > 0 then 1000 + e.misconception_severity * 10
      when e.due_review then 900
      when coalesce(e.evidence_count, 0) = 0 then 800 - e.sequence
      when e.mastery_average < 0.55 then 700
      when coalesce(e.transfer, 0) < 0.65 then 600
      when coalesce(e.retention, 0) < 0.65 and coalesce(e.evidence_count, 0) >= 2 then 550
      else 300 - e.sequence
    end as priority_score
  from eligible e
),
selected as (
  select *
  from ranked
  order by priority_score desc, sequence asc
  limit 1
)
select
  chosen.id as track_id,
  chosen.slug as track_slug,
  chosen.name as track_name,
  selected.concept_id,
  selected.concept_title,
  coalesce(selected.preferred_course_id, q.course_id) as course_id,
  crs.name as course_name,
  q.id as question_id,
  selected.sequence,
  selected.phase,
  case
    when selected.misconception_severity > 0 then 'debug'
    when selected.due_review then 'retention'
    when coalesce(selected.evidence_count, 0) = 0 then 'diagnostic'
    when selected.mastery_average < 0.55 then 'practice'
    when coalesce(selected.transfer, 0) < 0.65 then 'transfer'
    when coalesce(selected.retention, 0) < 0.65 then 'retention'
    else 'oral_defense'
  end as mission_type,
  case
    when selected.misconception_severity > 0
      then 'Encuentra y corrige el error conceptual antes de añadir complejidad nueva.'
    when selected.due_review
      then 'Recupera el concepto desde memoria y úsalo sin mirar primero la referencia.'
    when coalesce(selected.evidence_count, 0) = 0
      then 'Construye una línea base: define el concepto, sus supuestos y cuándo lo usarías.'
    when selected.mastery_average < 0.55
      then 'Resuelve un caso y explica cada decisión, no solo el resultado.'
    when coalesce(selected.transfer, 0) < 0.65
      then 'Transfiere el concepto a un problema distinto del ejemplo donde lo aprendiste.'
    when coalesce(selected.retention, 0) < 0.65
      then 'Demuestra retención sin apoyo y conecta el concepto con una decisión real.'
    else 'Defiende el concepto: supuestos, trade-offs, condiciones de fallo y alternativa.'
  end as objective,
  case
    when selected.misconception_severity > 0
      then 'Existe una misconception abierta; corregirla tiene prioridad sobre contenido nuevo.'
    when selected.due_review
      then 'La repetición espaciada está vencida y la retención debe comprobarse ahora.'
    when coalesce(selected.evidence_count, 0) = 0
      then 'Aún no existe evidencia propia para este nodo del track.'
    when selected.mastery_average < 0.55
      then 'La evidencia disponible todavía es demasiado débil para desbloquear el siguiente nodo.'
    when coalesce(selected.transfer, 0) < 0.65
      then 'El conocimiento existe, pero falta demostrar transferencia.'
    when coalesce(selected.retention, 0) < 0.65
      then 'El siguiente riesgo es olvidar o depender de apoyo inmediato.'
    else 'La evidencia base es suficiente; toca defender y conectar el conocimiento.'
  end as reason,
  case
    when selected.misconception_severity > 0 then 'conceptual'
    when selected.due_review then 'retention'
    when coalesce(selected.evidence_count, 0) = 0 then 'conceptual'
    when selected.mastery_average < 0.55 then 'coding'
    when coalesce(selected.transfer, 0) < 0.65 then 'transfer'
    when coalesce(selected.retention, 0) < 0.65 then 'retention'
    else 'conceptual'
  end as target_dimension,
  selected.concept_difficulty::smallint as difficulty,
  case
    when selected.misconception_severity > 0 then 3
    when selected.due_review then 1
    when coalesce(selected.evidence_count, 0) = 0 then 1
    when selected.mastery_average < 0.55 then 2
    when coalesce(selected.transfer, 0) < 0.65 then 2
    when coalesce(selected.retention, 0) < 0.65 then 1
    else 0
  end::smallint as assistance_ceiling,
  round(selected.mastery_average, 4) as mastery_average,
  coalesce(selected.evidence_count, 0)::integer as evidence_count,
  selected.due_review,
  (selected.misconception_severity > 0) as open_misconception
from chosen
join selected on selected.track_id = chosen.id
left join lateral (
  select qb.id, qb.course_id
  from public.sds_question_bank qb
  where qb.concept_id = selected.concept_id
    and qb.active
  order by
    (qb.course_id = selected.preferred_course_id) desc,
    (qb.dimension = case
      when selected.due_review then 'retention'
      when coalesce(selected.transfer, 0) < 0.65 then 'transfer'
      else 'conceptual'
    end) desc,
    qb.difficulty
  limit 1
) q on true
left join public.sds_courses crs on crs.id = coalesce(selected.preferred_course_id, q.course_id);
$$;

revoke execute on function public.sds_meta_professor_next_mission(text) from public, anon;
grant execute on function public.sds_meta_professor_next_mission(text) to authenticated;
